# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcf9cc70bfba09f8e108a3a427c20337c55231aebb038e04b6d88245101dcc9eafac966c8714619a343cf5d663a0baf0011e6d837fca87c2923fd91d398d83c3

test:
  secret_key_base: d1e5817347daaddb2923eef1dc6868e88fcbff98931dfc1d1c589813cb510727c664bee0f09efd8dae80ecdbf07e933d16515f4d43f07ceb4414f3beb9cbb460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
